name: project_cleanarchiteture
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  intl: ^0.18.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  google_fonts: ^4.0.2
  graphql_flutter: any
  graphql_codegen: any
  cached_network_image: any
  shimmer: any
  timeago: any

  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  go_router: ^10.0.0
  lottie: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  shared_preferences: ^2.2.0
  

  change_app_package_name: ^1.1.0

  cupertino_icons: ^1.0.2
  formz: ^0.6.0
  flutter_local_notifications: ^15.1.1
  app_settings: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
